### ISSUE TITLE
Error - Cannot Find Temp.bat

### ISSUE THREAD

**Issue by DomAmato** [ShiftMediaProject/FFmpeg#5]
When I try to run the project generate to make new project files it throws an error, I assume it has to be that I don't have all the dependencies downloaded but its not super clear which ones

![capture](https://cloud.githubusercontent.com/assets/6936055/10269973/f94a1ace-6aa9-11e5-88ea-299fc7869f61.PNG)

**Comment by cxsup** [comment]
The bin\log.txt file should have more info about the issue. The temp.bat error is a side-effect of other issues such as missing headers.  See my comments in the following thread:  https://github.com/ShiftMediaProject/FFmpeg/issues/4#issuecomment-145256110

Also, a successful install of Intel INDE will set the INTELMEDIASDKROOT envar.
https://software.intel.com/en-us/articles/installing-and-running-intel-media-sdk-2014-on-windows
https://software.intel.com/en-us/intel-inde
Of course, it's not required to have the Intel feature enabled (--enable-libmfx)

**Comment by Sibras** [comment]
As above. For a start you clearly dont have the Intel Media SDK installed. Any other missing dependencies will be listed in log.txt.
For instructions on installing dependencies see the readme.txt for project_generator.

**Comment by DomAmato** [comment]
That script works well from that thread in terms of grabbing libraries, @cxsup you guys should add that in the SMP folder since its way easier than grabbing all the dependencies  but I still get an error about missing xvid.h even though the dependency was downloaded and the file should be at the same location as other dependencies

**Comment by cxsup** [comment]
Regarding placement of *build.sh*, I'm using the following directory layout:

```
SMP\
     2015-08-10\
     2015-09-21\
     ...
     2015-10-05\
        git\
            bzip2\
            enca\
            ...
            zlib\
            build.sh
        msvc64\
            bin\
```
Also, create the mscv64/bin folder ahead of time since one of the projects (I forgot which) erroneously creates a file named *bin* instead of the required directory.

For the missing headers, see the following comment : [ append the  c:\...\msvc64\include  path to the  INCLUDE  environment variable ](https://github.com/ShiftMediaProject/FFmpeg/issues/4#issuecomment-145128959)

**Comment by Sibras** [comment]
Next on the todo list is to add a script to auto download and update all the other repos aswell as a combined solution file with all projects included.

Note though that I recently updated the output folders so there is no longer a msvc32 and msvc64 folder. The reasons for the separation was fixed along time ago and unifying them makes distributing the resulting output much simpler (providing pre-compiled binaries is also on the todo list).

**Comment by cxsup** [comment]
Feel free to adopt the script I posted here: https://github.com/ShiftMediaProject/FFmpeg/issues/4#issuecomment-145131181

**Comment by Sibras** [comment]
Thanks, I do prefer bash scripts although with this one I also wanted to have one that didnt need a msys environment installed. Which means ill have to write a windows batch file.

**Comment by Sibras** [comment]
Also DomAmato in what context are you using project generate? You only need to use this if you want to create an FFmpeg build with different options than the ones already provided. So if you dont have the dependency libraries then you can just remove the options to enable those libs.

**Comment by DomAmato** [comment]
I am trying to build a project that doesn't have a gpl licence so that it can be integrated as an addon for openframeworks. It will need both the libs and dlls built. I am debating what dependencies are needed but ideally it would have the most functionality possible while still having an lgpl licence

**Comment by Sibras** [comment]
Fair enough. Well theres now a batch file in the repo called "project_get_dependencies.bat" that will automatically download all the SMP supplied dependency repositories. This same script can also be used to check for and get any updates made to these libraries.

To ease building dependencies there is a new additional ffmpeg_deps.sln that contains links to all dependency projects so that they can all be built all at once (its set up so any dependency libs for a selected project will be auto built).

Lastly I also added some batch files to reconfigure the project based on a desired license version (note: not using noredist looses fdk,nvenc. not using gpl losses several filters as well as x264,x265,xvid,cdio)
